2023-08-31 14:48:11,996 [DEBUG]: An error occurred: Action was not a number
Traceback (most recent call last):
  File "F:\Projects\PythonCalculator\app.py", line 49, in calculate
    raise ValueError("Action was not a number")
ValueError: Action was not a number
2023-08-31 14:49:36,267 [DEBUG]: An error occurred: Action was not a number
Traceback (most recent call last):
  File "F:\Projects\PythonCalculator\app.py", line 80, in start_program
    raise ValueError("Action was not a number")
ValueError: Action was not a number
